name: kms_monitoring_iot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  http: ^1.5.0
  encrypt: ^5.0.3
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.1.0
  network_info_plus: ^6.0.1
  intl: ^0.18.0
  mobile_scanner: ^7.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
